quarkus:
  datasource:
    db-kind: postgresql
    username: ${DB_USER:animals}
    password: ${DB_PASSWORD:animals}
    jdbc:
      url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:animals}
      max-size: 100
db:
  cleanup:
    cron: 0 * * * * ?