FROM gcr.io/distroless/java17:nonroot
ARG APP_DIR=/application
ARG UID=1001

USER root
WORKDIR ${APP_DIR}
ENV LANGUAGE='en_US:en'

COPY --chmod=755 target/quarkus-app/lib/ ${APP_DIR}/lib
COPY --chmod=755 target/quarkus-app/*.jar ${APP_DIR}
COPY --chmod=755 target/quarkus-app/app/ ${APP_DIR}/app
COPY --chmod=755 target/quarkus-app/quarkus/ ${APP_DIR}/quarkus

USER ${UID}:${UID}
ENTRYPOINT [ \
  "java", \
  "-jar", \
  "quarkus-run.jar" \
]